// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw69ZVD0uBecFHmzR3LCqQCb6Tr0d-D4M',
    appId: '1:954743790700:web:aaa4a369a88ec39b6ecc49',
    messagingSenderId: '954743790700',
    projectId: 'recipe-explorer-5ae68',
    authDomain: 'recipe-explorer-5ae68.firebaseapp.com',
    storageBucket: 'recipe-explorer-5ae68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEbdS0CIyhJ4Yg8Ym7QYwafWYMtZITtXI',
    appId: '1:954743790700:android:42d5505bdf7573556ecc49',
    messagingSenderId: '954743790700',
    projectId: 'recipe-explorer-5ae68',
    storageBucket: 'recipe-explorer-5ae68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA46XSe7cmKtqbxT1nrWHIKQ4roa1eZeo4',
    appId: '1:954743790700:ios:dd28cea7ac020ec86ecc49',
    messagingSenderId: '954743790700',
    projectId: 'recipe-explorer-5ae68',
    storageBucket: 'recipe-explorer-5ae68.firebasestorage.app',
    iosBundleId: 'com.example.tlProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw69ZVD0uBecFHmzR3LCqQCb6Tr0d-D4M',
    appId: '1:954743790700:web:a2f117a05655b0af6ecc49',
    messagingSenderId: '954743790700',
    projectId: 'recipe-explorer-5ae68',
    authDomain: 'recipe-explorer-5ae68.firebaseapp.com',
    storageBucket: 'recipe-explorer-5ae68.firebasestorage.app',
  );
}
